// @ts-check
import { entreeDefineRules } from "../entree-utils.js";
// @ts-expect-error: No type definition
import reactHooks from "eslint-plugin-react-hooks";

/**
 * WIP. For now, only the rules generated by `npm create vite@latest ./ -- --template react-ts` are added.
 */
export function react() {
    const rules = entreeDefineRules({
        // ...react_base(),
        // ...react_essential(),
        // ...react_strongly_recommended(),
        // ...react_recommended(),
        // ...react_uncategorized(),
        // ...react_extension_rules_forTemplateExpressions(),
        ...(/** @type {any} */ (reactHooks.configs.recommended.rules)),
        "react-refresh/only-export-components": [
            "warn",
            { allowConstantExport: true, },
        ],
    });

    return rules;
}
