name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [changeset-release/main]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}

jobs:
  ci:
    name: Build, Check, Test
    runs-on: ubuntu-latest
    # Run on all PRs, pushes to changeset release branch, and manual dispatch
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/changeset-release/main') ||
      github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/build

      - name: Run type check
        run: pnpm run type-check

      - name: Run tests
        run: pnpm run test
