name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}

jobs:
  ci:
    name: Build, Check, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/build

      - name: Run type check
        run: pnpm run type-check

      - name: Run tests
        run: pnpm run test
